### ISSUE TITLE
Issue in Input.java

### ISSUE THREAD

**Issue by KindlySoul** [Red5/red5-io#18]
In the file org/red5/io/amf3/Input.java we have this code:
```
	if (attributes == null) 
	{
		attributes = new ArrayList<String>(count);
		for (int i = 0; i < count; i++) {
			attributes.add(readString(String.class));
		}
		refStorage.classReferences.add(new ClassReference(className, AMF3.TYPE_OBJECT_VALUE, attributes));
	}
	//use the size of the attributes if we have no count
	if (count == 0 && attributes != null) {
		count = attributes.size();
		log.debug("Using class attribute size for property count: {}", count);
		//read the attributes from the stream and log if count doesnt match
		List<String> tmpAttributes = new ArrayList<String>(count);
		for (int i = 0; i < count; i++) {
			tmpAttributes.add(readString(String.class));
		}
		if (count != tmpAttributes.size()) {
			log.debug("Count and attributes length does not match!");
		}		
		refStorage.classReferences.add(new ClassReference(className, AMF3.TYPE_OBJECT_VALUE, attributes));
	}
```
If attributes is null and count==0 we'll add new ClassReference to the refStorage twice. It's wrong and leads to errors when in complex objects serialization.

**Comment by mondain** [comment]
Looks correct to me; if attributes is null then add reference (1 instance) or if count is zero AND attributes are null then add a reference (1 instance). The second if block doesn't trigger if the first one does.

**Comment by KindlySoul** [comment]
In this cоndition 
if (count == 0 && attributes != null)
attributes will never null because we have this condition earlier:
if (attributes == null) 
 {
        attributes = new ArrayList<String>(count);
...
}

**Comment by mondain** [comment]
Ah right, good catch; I wonder what the author meant to do here...

**Comment by KindlySoul** [comment]
Thanks for the fix! But why do we need additional checks (attributes != null)? As we have already discussed after first check attributes will never be null.

**Comment by mondain** [comment]
Just a habit and being extra cautious
