### ISSUE TITLE
Upgrade isoparser version

### ISSUE THREAD

**Issue by t2y** [Red5/red5-io#7]
Red5 uses isoparser to read metadata in media file and its version is **1.0-RC-19-SNAPSHOT**. I found this version is quite old and many improvements are added recently.
- https://github.com/sannies/mp4parser/releases
- http://mvnrepository.com/artifact/com.googlecode.mp4parser/isoparser

Update isoparser for robustness to parse metadata.

**Comment by opoplawski** [comment]
Isn't it here: http://mvnrepository.com/artifact/com.googlecode.mp4parser/isoparser/1.0.5.4?

**Comment by mondain** [comment]
It was pushed to the maven repo after our release. https://github.com/sannies/mp4parser/issues/35
